################################################
# Copyright 2019, Yahoo Inc.
# Licensed under the Apache License, Version 2.0
# See LICENSE file in project root for terms.
################################################

elide:
  baseUrl: ${PASS_CORE_BASE_URL}
  json-api:
    path: /data
    enabled: true
    links:
      enabled: true
  graphql:
    enabled: false
  api-docs:
    path: /doc
    enabled: true
    version: openapi_3_1
  async:
    enabled: false
  aggregation-store:
    default-dialect: Postgres

spring:
  application:
    name: pass-core
  cloud:
    aws:
      dynamodb:
        enabled: false
      parameterstore:
        enabled: false
      s3:
        enabled: false
      secretsmanager:
        enabled: false
      ses:
        enabled: false
      sns:
        enabled: false
      sqs:
        enabled: false
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: ${PASS_CORE_DATABASE_URL}
    username: ${PASS_CORE_DATABASE_USERNAME}
    password: ${PASS_CORE_DATABASE_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/core-changelog.yaml'
    parameters:
      institution-changelog-file: ${PASS_CORE_INSTN_CHG_LOG:file:////tmp/instn-changelog.yaml}
  security:
    saml2:
      relyingparty:
        registration:
          pass:
            entity-id: ${PASS_CORE_SP_ID}
            signing:
              credentials:
                - private-key-location: ${PASS_CORE_SP_KEY}
                  certificate-location: ${PASS_CORE_SP_CERT}
            decryption:
              credentials:
                - private-key-location: ${PASS_CORE_SP_KEY}
                  certificate-location: ${PASS_CORE_SP_CERT}
            acs:
              location: ${PASS_CORE_SP_ACS}
            assertingparty:
              metadata-uri: ${PASS_CORE_IDP_METADATA}
    user:
      name: ${PASS_CORE_USER}
      password: ${PASS_CORE_PASSWORD}
      roles: BACKEND
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: ${PASS_CORE_PORT}
  shutdown: graceful

logging:
  file:
    path: ${PASS_CORE_LOG_DIR:${java.io.tmpdir}/pass-core}

aws:
  region: us-east-1

pass:
  app-location: ${PASS_CORE_APP_LOCATION:classpath:app/}
  auth:
    attribute-map:
      DISPLAY_NAME: 'urn:oid:2.16.840.1.113730.3.1.241'
      SCOPED_AFFILIATION: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.9'
      EMAIL: 'urn:oid:0.9.2342.19200300.100.1.3'
      EPPN: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
      GIVEN_NAME: 'urn:oid:2.5.4.42'
      SURNAME: 'urn:oid:2.5.4.4'
      EMPLOYEE_ID: 'urn:oid:2.16.840.1.113730.3.1.3'
      UNIQUE_ID: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.13'
  csp: ${PASS_CORE_APP_CSP}
  file-service:
    storage-type: ${PASS_CORE_FILE_SERVICE_TYPE:FILE_SYSTEM}
    root-dir: ${PASS_CORE_FILE_SERVICE_ROOT_DIR:}
    s3-bucket-name: ${PASS_CORE_S3_BUCKET_NAME:pass-core-file}
    s3-repo-prefix: ${PASS_CORE_S3_REPO_PREFIX:pass-core-file}
  jms:
    queue:
      submission: ${PASS_CORE_SUBMISSION_QUEUE:pass-submission}
      deposit: ${PASS_CORE_DEPOSIT_QUEUE:pass-deposit}
      submission-event: ${PASS_CORE_SUBMISSION_EVENT_QUEUE:pass-submission-event}
    sqs: ${PASS_CORE_USE_SQS:true}
    embed: ${PASS_CORE_EMBED_JMS_BROKER:false}
  default-login-success-url: ${PASS_CORE_DEFAULT_LOGIN_SUCCESS}
  login-processing-path: ${PASS_CORE_LOGIN_PROCESSING_PATH}
  logout-delete-cookies: ${PASS_CORE_LOGOUT_DELETE_COOKIES}
  logout-success-url: ${PASS_CORE_LOGOUT_SUCCESS}
  policy:
    institution: ${PASS_CORE_POLICY_INSTITUTION}
    institutional_policy_title: ${PASS_CORE_POLICY_INSTITUTIONAL_POLICY_TITLE}
    institutional_repository_name: ${PASS_CORE_POLICY_INSTITUTIONAL_REPOSITORY_NAME}
  usertoken:
    key: ${PASS_CORE_USERTOKEN_KEY}
