################################################
# Copyright 2019, Yahoo Inc.
# Licensed under the Apache License, Version 2.0
# See LICENSE file in project root for terms.
################################################

elide:
  baseUrl: ${PASS_CORE_BASE_URL:http://localhost:8080}
  json-api:
    path: /data
    enabled: true
    links:
      enabled: true
  graphql:
    enabled: false
  api-docs:
    path: /doc
    enabled: true
    version: openapi_3_1
  async:
    enabled: false
  aggregation-store:
    enabled: false

spring:
  application:
    name: pass-core
  artemis:
    embedded:
      enabled: ${PASS_CORE_EMBED_JMS_BROKER:true}
      queues: pass-submission,pass-deposit,pass-submission-event
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.H2Dialect'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/core-changelog.yaml'
    parameters:
      institution-changelog-file: ${PASS_CORE_INSTN_CHG_LOG:file:////tmp/instn-changelog.yaml}
  security:
    saml2:
      relyingparty:
        registration:
          pass:
            entity-id: ${PASS_CORE_SP_ID:https://sp.pass/shibboleth}
            signing:
              credentials:
                - private-key-location: ${PASS_CORE_SP_KEY:classpath:saml2/sp-key.pem}
                  certificate-location: ${PASS_CORE_SP_CERT:classpath:saml2/sp-cert.pem}
            decryption:
              credentials:
                - private-key-location: ${PASS_CORE_SP_KEY:classpath:saml2/sp-key.pem}
                  certificate-location: ${PASS_CORE_SP_CERT:classpath:saml2/sp-cert.pem}
            acs:
              location: ${PASS_CORE_SP_ACS:{baseUrl}/login/saml2/sso/{registrationId}}
            assertingparty:
              metadata-uri: ${PASS_CORE_IDP_METADATA:classpath:saml2/idp-metadata.xml}
    user:
      name: ${PASS_CORE_USER:backend}
      password: ${PASS_CORE_PASSWORD:moo}
      roles: BACKEND
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080
  shutdown: graceful

logging:
  file:
    path: ${PASS_CORE_LOG_DIR:${java.io.tmpdir}/pass-core}

aws:
  region: us-east-1
  sqs:
    endpoint-override: ${AWS_SQS_ENDPOINT_OVERRIDE:}

pass:
  app-location: ${PASS_CORE_APP_LOCATION:classpath:app/}
  auth:
    attribute-map:
      DISPLAY_NAME: 'urn:oid:2.16.840.1.113730.3.1.241'
      SCOPED_AFFILIATION: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.9'
      EMAIL: 'urn:oid:0.9.2342.19200300.100.1.3'
      EPPN: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6'
      GIVEN_NAME: 'urn:oid:2.5.4.42'
      SURNAME: 'urn:oid:2.5.4.4'
      EMPLOYEE_ID: 'urn:oid:2.16.840.1.113730.3.1.3'
      UNIQUE_ID: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.13'
  csp: ${PASS_CORE_APP_CSP:default-src 'self';}
  file-service:
    storage-type: 'FILE_SYSTEM'
  jms:
    queue:
      submission: ${PASS_CORE_SUBMISSION_QUEUE:pass-submission}
      deposit: ${PASS_CORE_DEPOSIT_QUEUE:pass-deposit}
      submission-event: ${PASS_CORE_SUBMISSION_EVENT_QUEUE:pass-submission-event}
    sqs: ${PASS_CORE_USE_SQS:false}
    embed: ${PASS_CORE_EMBED_JMS_BROKER:true}
  default-login-success-url: ${PASS_CORE_DEFAULT_LOGIN_SUCCESS:/app/}
  login-processing-path: ${PASS_CORE_LOGIN_PROCESSING_PATH:/login/saml2/sso/{registrationId}}
  logout-delete-cookies: ${PASS_CORE_LOGOUT_DELETE_COOKIES:JSESSIONID /}
  logout-success-url: ${PASS_CORE_LOGOUT_SUCCESS:/login}
  policy:
    institution: ${PASS_CORE_POLICY_INSTITUTION:johnshopkins.edu}
    institutional_policy_title: ${PASS_CORE_POLICY_INSTITUTIONAL_POLICY_TITLE:Johns Hopkins University (JHU) Open Access Policy}
    institutional_repository_name: ${PASS_CORE_POLICY_INSTITUTIONAL_REPOSITORY_NAME:JScholarship}
  usertoken:
    key: ${PASS_CORE_USERTOKEN_KEY:}

---
elide:
  aggregation-store:
    default-dialect: Postgres

spring:
  config:
    activate:
      on-profile: "production"
  jpa:
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: ${PASS_CORE_DATABASE_URL}
    username: ${PASS_CORE_DATABASE_USERNAME}
    password: ${PASS_CORE_DATABASE_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  security:
    user:
      name: ${PASS_CORE_USER}
      password: ${PASS_CORE_PASSWORD}
      roles: BACKEND

server:
  port: ${PASS_CORE_PORT}

pass:
  jms:
    sqs: ${PASS_CORE_USE_SQS:true}
  file-service:
    storage-type: ${PASS_CORE_FILE_SERVICE_TYPE:FILE_SYSTEM}
    root-dir: ${PASS_CORE_FILE_SERVICE_ROOT_DIR:}
    s3-bucket-name: ${PASS_CORE_S3_BUCKET_NAME:pass-core-file}
    s3-repo-prefix: ${PASS_CORE_S3_REPO_PREFIX:pass-core-file}
    s3-endpoint: ${PASS_CORE_S3_ENDPOINT:}
