name: Test SQ - Run Analysis on Main branch

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Print description
        run: |
          echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
          echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests
        run: mvn -U -B -V -ntp verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.branch.name=main -Dsonar.token=${{ secrets.SONAR_TOKEN }}