name: Continuous Integration
on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: "Run Unit & Integration Tests"
    uses: eclipse-pass/main/.github/workflows/ci.yml@main

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Print description
        run: |
          echo "Running SonarQube Scanner"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        secret: inherit
