name: Continuous Integration
on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: "Run Unit & Integration Tests"
    uses: eclipse-pass/main/.github/workflows/ci.yml@main

  sonarqube:
    needs: [test]
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-build
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=eclipse-pass_pass-core
            -Dsonar.organization=eclipse-pass
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
