# Release artifact will be pushed to Sonatype, which is synced to Maven Central
# Build artifacts get pushed to Sonatype and non-SNAPSHOT versions are then
# auto-synced to Maven Central
name: Publish a release to Maven Central

on:
  # We can use very similiar workflow to manually trigger a full publish
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
      nextversion:
        description: 'Next dev version'
        required: true

# Will need to have someone with admin permissions to add some secrets:
# Credentials for Sonatype, needs a Sonatype account.
#   - OSSRH_USERNAME
#   - OSSRH_TOKEN
# Will need GPG key + passphrase to sign artifacts for Maven Central
#   - MAVEN_GPG_PASSPHRASE
#   - MAVEN_GPG_KEY
# 
# Should be able to use secrets.GITHUB_TOKEN to push images to GHCR, this
# secret is provided automatically to the workflow
# 
# May need a GH PAT (likely fine-grained) in order to update pass-docker with
# new image refs
# (Not yet used)
#   - GH_USER
#   - GH_PAT
# 
# Using maven with arguments:
#   -B (--batch-mode) non-interactive batch mode
#   -U force dependency update
#   -V print maven version without stopping build
#   -ntp (--no-transfer-progress) do not show download progress

jobs:
  publish:
    runs-on: ubuntu-latest
    # Can we check to make sure $NEXT doesn't already exist as a tag?
    steps:
      # =============================================================================
      # Setup
      # =============================================================================
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "GH Action | Release"
          git config user.email "<>"

      - name: Setup Java & Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: ossrh
          # User/pass refer to ENV VARs set below
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      # =============================================================================
      # Start the work
      # =============================================================================
      # This versions:update-parent will grab the latest release (non-snapshot)
      - name: Bump version to release
        run: mvn -B -U -V -ntp versions:set -DnewVersion=${{ inputs.releaseversion }}

      - name: Commit release version bump
        run: |
          git add **/pom.xml pom.xml
          git commit -m "Update pom versions to ${{ inputs.releaseversion }}"

      # Will publish and create new Docker image for release version
      - name: Publish release
        run: |
          mvn -B -U -V -ntp release:prepare -DreleaseVersion=$RELEASE -Dtag=$RELEASE -DdevelopmentVersion=$NEXT -DautoVersionSubmodules=true
          mvn -B -U -V -ntp release:perform -P release 
        env:
          # Add OSSRH_USERNAME and OSSRH_PASSWORD as GH secrets
          # https://docs.github.com/en/actions/security-guides/encrypted-secrets
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          RELEASE: ${{ inputs.releaseversion }}
          NEXT: ${{ inputs.nextversion }}

      - name: Update to new dev version
        run: |
          mvn -B -U -V -ntp versions:set -DnewVersion=${{ inputs.nextversion }} -DallowSnapshots=true
      
      - name: Commit snapshot version bump
        run: |
          git add **/pom.xml pom.xml
          git commit -m "Update pom versions to ${{ inputs.nextversion }}"

      # Will produce a new Docker image for the new dev version
      - name: Build and publish new dev version
        run: mvn -B -U -V -ntp clean deploy -P release

      - name: Push to updated main and new release tag GH
        run: |
          git push origin main
          git push origin --tags

      # Check docker images
      - name: Check local Docker images
        run: docker images
      # Handle Docker images
      # - name: Login to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Push Docker image to GHCR
      #   run: |
      #     docker push ghcr.io/eclipse-pass/pass-core-main:${{ inputs.releaseversion }}
      #     docker push ghcr.io/eclipse-pass/pass-core-main:${{ inputs.nextversion }}
