name: Publish SNAPSHOT

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  snapshot:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: eclipse-pass/main/.github/workflows/snapshot.yml@main
    secrets: inherit
    with:
      images: ghcr.io/eclipse-pass/pass-core-main
