name: Publish SNAPSHOT

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  snapshot:
    uses: eclipse-pass/main/.github/workflows/snapshot.yml@main
    secrets: inherit
    with:
      images: ghcr.io/eclipse-pass/pass-core-main
